// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmk3r_6zFzgucNHw-9fp58AOjIITPmS54',
    appId: '1:642153504200:web:634674c2e5c59faa2434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    authDomain: 'project6-a1c9a.firebaseapp.com',
    storageBucket: 'project6-a1c9a.firebasestorage.app',
    measurementId: 'G-73C48ZXGCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfUHW1m_dYCJGLsUnV5yqUrRvIPOUSo0',
    appId: '1:642153504200:android:3d57e0eb15c17a422434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    storageBucket: 'project6-a1c9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpopVyZSmloyow1lfpGUxgjC4vDvlP9F0',
    appId: '1:642153504200:ios:e71eb974db5e905c2434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    storageBucket: 'project6-a1c9a.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpopVyZSmloyow1lfpGUxgjC4vDvlP9F0',
    appId: '1:642153504200:ios:e71eb974db5e905c2434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    storageBucket: 'project6-a1c9a.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4niAxX48tAzo5KjX5rNh6_TbcYb6U_Dk',
    appId: '1:642153504200:web:73e41bfc3e869afc2434fd',
    messagingSenderId: '642153504200',
    projectId: 'project6-a1c9a',
    authDomain: 'project6-a1c9a.firebaseapp.com',
    storageBucket: 'project6-a1c9a.firebasestorage.app',
    measurementId: 'G-X36D1ZEYQB',
  );
}
